In [1]:
# Let's import the pandas, numpy libraries as pd, and np respectively. 
import pandas as pd
import numpy  as np

# Load the pyplot collection of functions from matplotlib, as plt 
import matplotlib.pyplot as plt
#Import Seaborn for data visualization
import seaborn as sns
import scipy.stats as stats
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier


In [2]:
datafile_expired='expired.csv'
df_expired = pd.read_csv(datafile_expired)

In [3]:
datafile_expired='nonexpired.csv'
df_nonexpired = pd.read_csv(datafile_expired)

In [4]:
df_expired.diabetesMed.sort_values()

1210     No
835      No
837      No
838      No
839      No
       ... 
956     Yes
955     Yes
954     Yes
911     Yes
2420    Yes
Name: diabetesMed, Length: 2421, dtype: object

In [5]:
# Encode to set Yes = 1 and No = 0
for i in range(len(df_expired['diabetesMed'])):
    if df_expired['diabetesMed'].iloc[i] == 'Yes':
        df_expired['diabetesMed'].iloc[i] = 1
    else:
        df_expired['diabetesMed'].iloc[i] = 0
        

/Users/sachinsharma/opt/anaconda3/lib/python3.9/site-packages/pandas/core/indexing.py:1732: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)


In [6]:
# Encode to set Yes = 1 and No = 0 in the Non-Expired Group
df_nonexpired['diabetesMed'] = np.where(df_nonexpired['diabetesMed'] == 'No', 0, df_nonexpired['diabetesMed'])
df_nonexpired['diabetesMed'] = np.where(df_nonexpired['diabetesMed'] == 'Yes', 1, df_nonexpired['diabetesMed'])



In [7]:
df_expired['diabetesMed'].unique()

array([1, 0], dtype=object)

In [8]:
df_nonexpired['diabetesMed'].value_counts()

1    76721
0    22624
Name: diabetesMed, dtype: int64

In [9]:
df_expired['change'].unique()

array(['No', 'Ch'], dtype=object)

In [10]:
# Encode to Change so 'No'= 0 and 'Ch' = 1
for i in range(len(df_expired['change'])):
    if df_expired['change'][i] == 'Ch':
        df_expired['change'][i] = 1
    else:
        df_expired['change'][i] = 0
    

/var/folders/j5/np658np12vl9nkcgdxj9xmv00000gn/T/ipykernel_3340/1802009903.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_expired['change'][i] = 0
/var/folders/j5/np658np12vl9nkcgdxj9xmv00000gn/T/ipykernel_3340/1802009903.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_expired['change'][i] = 1


In [11]:
df_expired['change'].unique()

array([0, 1], dtype=object)

In [12]:
# Encode Change feature to 'No'= 0 and 'Ch' = 1 in the Non-Expired Group
df_nonexpired['change'] = np.where(df_nonexpired['change'] == 'No', 0, df_nonexpired['change'])
df_nonexpired['change'] = np.where(df_nonexpired['change'] == 'Ch', 1, df_nonexpired['change'])


In [13]:
df_nonexpired['change'].value_counts()

0    53222
1    46123
Name: change, dtype: int64

In [14]:
# Change column values for features containing DM meds.  If they are on the medication then value gets changed to 1. If they are not on the med it gets changed to 0.
meds =['metformin','repaglinide','nateglinide','chlorpropamide','glimepiride','acetohexamide','glipizide','glyburide','tolbutamide','pioglitazone','rosiglitazone','acarbose','miglitol','troglitazone','tolazamide','examide','citoglipton','insulin','glyburide-metformin','glipizide-metformin','glimepiride-pioglitazone','metformin-rosiglitazone','metformin-pioglitazone']
for i in meds :
    drugname = i
    drugname= ''+drugname+''
    df_expired[drugname] = np.where(df_expired[drugname] == 'No', 0, df_expired[drugname])
    df_expired[drugname] = np.where(df_expired[drugname] == 'Up', 1, df_expired[drugname])           
    df_expired[drugname] = np.where(df_expired[drugname] == 'Down', 1, df_expired[drugname]) 
    df_expired[drugname] = np.where(df_expired[drugname] == 'Steady', 1, df_expired[drugname])                      

In [15]:
# Change column values in Non-Expired for features containing DM meds.  If they are on the medication then value gets changed to 1. If they are not on the med it gets changed to 0.
meds =['metformin','repaglinide','nateglinide','chlorpropamide','glimepiride','acetohexamide','glipizide','glyburide','tolbutamide','pioglitazone','rosiglitazone','acarbose','miglitol','troglitazone','tolazamide','examide','citoglipton','insulin','glyburide-metformin','glipizide-metformin','glimepiride-pioglitazone','metformin-rosiglitazone','metformin-pioglitazone']
for i in meds :
    drugname = i
    drugname= ''+drugname+''
    df_nonexpired[drugname] = np.where(df_nonexpired[drugname] == 'No', 0, df_nonexpired[drugname])
    df_nonexpired[drugname] = np.where(df_nonexpired[drugname] == 'Up', 1, df_nonexpired[drugname])           
    df_nonexpired[drugname] = np.where(df_nonexpired[drugname] == 'Down', 1, df_nonexpired[drugname]) 
    df_nonexpired[drugname] = np.where(df_nonexpired[drugname] == 'Steady', 1, df_nonexpired[drugname])                      

In [16]:
df_nonexpired[meds].head()

metformin repaglinide nateglinide chlorpropamide glimepiride acetohexamide  \
0         0           0           0              0           0             0   
1         0           0           0              0           0             0   
2         0           0           0              0           0             0   
3         0           0           0              0           0             0   
4         0           0           0              0           0             0   

  glipizide glyburide tolbutamide pioglitazone  ... troglitazone tolazamide  \
0         0         0           0            0  ...            0          0   
1         0         0           0            0  ...            0          0   
2         0         0           0            0  ...            0          0   
3         0         0           0            0  ...            0          0   
4         0         0           0            0  ...            0          0   

  examide citoglipton insulin glyburide-metformin glipizide-metformin  \
0       0           0       0                   0                   0   
1       0           0       1                   0                   0   
2       0           0       0                   0                   0   
3       0           0       1                   0                   0   
4       0           0       1                   0                   0   

  glimepiride-pioglitazone metformin-rosiglitazone metformin-pioglitazone  
0                        0                       0                      0  
1                        0                       0                      0  
2                        0                       0                      0  
3                        0                       0                      0  
4                        0                       0                      0  

[5 rows x 23 columns]

In [17]:
df_expired['age'].unique()

array(['[80-90)', '[40-50)', '[70-80)', '[90-100)', '[50-60)', '[60-70)',
       '[30-40)', '[20-30)', '[10-20)', '[0-10)'], dtype=object)

Encode Age column to the following values:
[0-10), 0, 
[10-20),1, 
[20-30), 2,
[30-40),3, 
[40-50),4, 
[50-60), 5, 
[60-70), 6, 
[70-80), 7  
[80-90), 8
[90-100), 9

In [18]:
AgeList = []
AgeList = df_expired['age'].unique().tolist()
AgeList.sort()



In [19]:
#Encode Age feature in Expired Dataset.
for i in AgeList :
    AgeCat = i
    AgeCat = ''+AgeCat+''
    x = AgeList.index(i)
    df_expired['age'] = np.where(df_expired['age'] == AgeCat, x, df_expired['age'])
     


In [20]:
print(df_expired['age'].unique())

[8 4 7 9 5 6 3 2 1 0]


In [21]:
df_expired['age'].value_counts()

8    763
7    736
6    423
9    204
5    196
4     78
3     11
2      8
1      1
0      1
Name: age, dtype: int64

In [22]:
#Encode Age feature in Non-Expired Dataset.
for i in AgeList :
    AgeCat = i
    AgeCat = ''+AgeCat+''
    x = AgeList.index(i)
    df_nonexpired['age'] = np.where(df_nonexpired['age'] == AgeCat, x, df_nonexpired['age'])
 

In [23]:
df_nonexpired['age'].value_counts()

7    25332
6    22060
5    17060
8    16434
4     9607
3     3764
9     2589
2     1649
1      690
0      160
Name: age, dtype: int64

In [24]:
#Drop Features that are not relevant. "number of outpatient vists" was kept even though there was no statistical difference between the two.
df_expired.drop(columns=["race", "gender",'weight','payer_code','medical_specialty','max_glu_serum','A1Cresult','readmitted'], inplace=True)

In [25]:
#Do the same to non-expired group. 
df_nonexpired.drop(columns=["race", "gender",'weight','payer_code','medical_specialty','max_glu_serum','A1Cresult','readmitted'], inplace=True)

In [26]:
df_expired.columns

Index(['age', 'admission_type_id', 'discharge_disposition_id',
       'admission_source_id', 'time_in_hospital', 'num_lab_procedures',
       'num_procedures', 'num_medications', 'number_outpatient',
       'number_emergency', 'number_inpatient', 'diag_1', 'diag_2', 'diag_3',
       'number_diagnoses', 'metformin', 'repaglinide', 'nateglinide',
       'chlorpropamide', 'glimepiride', 'acetohexamide', 'glipizide',
       'glyburide', 'tolbutamide', 'pioglitazone', 'rosiglitazone', 'acarbose',
       'miglitol', 'troglitazone', 'tolazamide', 'examide', 'citoglipton',
       'insulin', 'glyburide-metformin', 'glipizide-metformin',
       'glimepiride-pioglitazone', 'metformin-rosiglitazone',
       'metformin-pioglitazone', 'change', 'diabetesMed',
       'discharge_disposition_description'],
      dtype='object')

In [27]:
df_nonexpired.columns

Index(['age', 'admission_type_id', 'discharge_disposition_id',
       'admission_source_id', 'time_in_hospital', 'num_lab_procedures',
       'num_procedures', 'num_medications', 'number_outpatient',
       'number_emergency', 'number_inpatient', 'diag_1', 'diag_2', 'diag_3',
       'number_diagnoses', 'metformin', 'repaglinide', 'nateglinide',
       'chlorpropamide', 'glimepiride', 'acetohexamide', 'glipizide',
       'glyburide', 'tolbutamide', 'pioglitazone', 'rosiglitazone', 'acarbose',
       'miglitol', 'troglitazone', 'tolazamide', 'examide', 'citoglipton',
       'insulin', 'glyburide-metformin', 'glipizide-metformin',
       'glimepiride-pioglitazone', 'metformin-rosiglitazone',
       'metformin-pioglitazone', 'change', 'diabetesMed',
       'discharge_disposition_description'],
      dtype='object')

In [28]:
#Create encoded variables for ICD codes
diag_1 = pd.get_dummies(df_expired['diag_1'], prefix='ICD1')
diag_2 = pd.get_dummies(df_expired['diag_2'],prefix='ICD2')
diag_3 = pd.get_dummies(df_expired['diag_3'],prefix='ICD3')

In [29]:
#Concat tables 
df_expired_concat = pd.concat([df_expired,diag_1, diag_2, diag_3], axis=1)

In [30]:
#Create encoded variables for Non-Expired ICD codes
diag_1 = pd.get_dummies(df_nonexpired['diag_1'], prefix='ICD1')
diag_2 = pd.get_dummies(df_nonexpired['diag_2'],prefix='ICD2')
diag_3 = pd.get_dummies(df_nonexpired['diag_3'],prefix='ICD3')

In [31]:
#Concat non_expired tables 
df_nonexpired_concat = pd.concat([df_nonexpired,diag_1, diag_2, diag_3], axis=1)

In [32]:
df_nonexpired_concat = df_nonexpired_concat.drop(columns=['diag_1','diag_2','diag_3','discharge_disposition_description'])
df_expired_concat = df_expired_concat.drop(columns=['diag_1','diag_2','diag_3','discharge_disposition_description'])


In [33]:
vertical_concat = pd.concat([df_expired_concat, df_nonexpired_concat], axis=0, ignore_index=True)


In [34]:
df = vertical_concat.fillna(0)

In [35]:
#Define the y variable as the discharge_disposition_id. 1=Expired,0=Non-expired
y = df['discharge_disposition_id']
X = df.drop('discharge_disposition_id', axis=1)

In [36]:
#Create a 70/30 train and test split.
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=42)

In [37]:
# Making a Scaler object
scaler = StandardScaler()

In [38]:
# Fitting data to the scaler object
X_train_scaled = scaler.fit_transform(X_train)


In [39]:
X_train_scaled.shape

(71236, 2289)

In [40]:
#Write dataframe to files. 
df.to_csv('df_modeling.csv', index=True)
df_nonexpired_concat.to_csv('feature1_nonexpired.csv', index=True)
df_expired_concat.to_csv('feature1_expired.csv', index=True)
